### ISSUE TITLE
OOM on DEBUG or finer levels with Splunk + Logback

### ISSUE THREAD

**Issue by jihor** [splunk/splunk-library-javalogging#22]
See:
https://github.com/jihor/splunk-oom-test

Start the project with [gradle run] or [gradle run -Dsplunk.token={your HTTP EC Token}]. Regardless of the token validity the JVM will encounter OOM in a couple minutes (memory growth can be easily observed with JMC). My guess is there is some issue in using Apache HTTP - FutureCallback.completed() invokes log.debug() which invokes new FutureCallback's execute() thus creating a loop that eventually leads to OOM.

I guess this is linked to the following call stack:

<pre>
"I/O dispatcher 1@3224" prio=5 tid=0x10 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at org.apache.http.nio.pool.AbstractNIOConnPool.getTotalStats(AbstractNIOConnPool.java:644)
      at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.formatStats(PoolingNHttpClientConnectionManager.java:218)
      at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.access$200(PoolingNHttpClientConnectionManager.java:92)
      at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.completed(PoolingNHttpClientConnectionManager.java:490)
      at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.completed(PoolingNHttpClientConnectionManager.java:476)
      at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
      at org.apache.http.nio.pool.RouteSpecificPool.completed(RouteSpecificPool.java:155)
      at org.apache.http.nio.pool.AbstractNIOConnPool.requestCompleted(AbstractNIOConnPool.java:498)
      at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.completed(AbstractNIOConnPool.java:806)
      at org.apache.http.impl.nio.reactor.SessionRequestImpl.completed(SessionRequestImpl.java:134)
      - locked <0xd99> (a org.apache.http.impl.nio.reactor.SessionRequestImpl)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.processNewChannels(AbstractIOReactor.java:426)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:289)
      at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
      at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
      at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by tdhellmann** [comment]
Unfortunately, we haven't been able to reproduce this on our end using your example. If this is still an issue, please let me know.

**Comment by jihor** [comment]
Wow, that was a long time ago.
I have updated my example, try running it and looking into `main-thread-events.log`
After ~10 events, the app will deadlock. Thread dump is:
[thread_dump.log](https://github.com/splunk/splunk-library-javalogging/files/2019227/thread_dump.log)
