### ISSUE TITLE
Unable to invoke factory method in class com.splunk.logging.HttpEventCollectorLog4jAppender

### ISSUE THREAD

**Issue by RacoonG47** [splunk/splunk-library-javalogging#266]
Hi, I have been trying to resolve the following issue, I have seen the error mentioned in the following issue(https://github.com/splunk/splunk-library-javalogging/issues/109) but the solution to the problem has not been specified, I am happy to send more info. Thanks in advance.

restartedMain ERROR Unable to invoke factory method in class com.splunk.logging.HttpEventCollectorLog4jAppender for element SplunkHttp: java.lang.IllegalArgumentException: Channel cannot be null or empty java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

Followed by this: 
restartedMain ERROR Null object returned for SplunkHttp in Appenders.
restartedMain ERROR root Root has no parameter that matches element Logger

**Comment by VinayakJamadar** [comment]
@RacoonG47 
Do you able to solve issue?
If yes please explain the solution
