### ISSUE TITLE
TCP port 15000, not working

### ISSUE THREAD

**Issue by skamtala** [splunk/splunk-library-javalogging#76]
I cloned this code and started testing with local  splunk. i had created a tcp input source on port 514 and started running the code after changing port to 514 (it was 15000) but having issues running these.
I am getting the below error, not sure if my setup is correct.

Running LogbackFunctionalTest
java.net.BindException: Permission denied (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at Util$1.run(Util.java:70)
	at java.lang.Thread.run(Thread.java:748)

**Comment by shakeelmohamed** [comment]
Hi @skamtala, which OS are you using? Ports under 1000 are typically privileged and require running any applications as sudo/root to access them.
