### ISSUE TITLE
Troubleshooting ClassNotFoundException

### ISSUE THREAD

**Issue by aedenj** [splunk/splunk-library-javalogging#84]
I'm using splunk logging within a Spark job and getting the following exception

```
Can't load log handler "com.splunk.logging.HttpEventCollectorLoggingHandler"
java.lang.ClassNotFoundException: com.splunk.logging.HttpEventCollectorLoggingHandler
java.lang.ClassNotFoundException: com.splunk.logging.HttpEventCollectorLoggingHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.util.logging.LogManager$5.run(LogManager.java:965)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.addLogger(LogManager.java:1165)
	at java.util.logging.LogManager.demandLogger(LogManager.java:556)
	at java.util.logging.Logger.demandLogger(Logger.java:455)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	... 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

My config file is

```
splunkLogger.level=INFO
splunkLogger.handlers=com.splunk.logging.HttpEventCollectorLoggingHandler
...
```
 I've tried setting the CLASSPATH to my jar file containing the spark job with no luck. 

I suspect maybe it's because I'm using maven's shade plugin to create an Uber jar. If that matters, how does one reference the class from the properties file?

Thanks.

**Comment by zenmoto** [comment]
This looks like a classloader problem, so it's not an issue with the logging library.  I'd guess that the problem is probably with how you are building your jar with the shade plugin- in particular if you are using the `<minimizeJar>true</minimizeJar>`, the shade plugin may not be able to determine that you have a dependency on `HttpEventCollectorLoggingHandler`.  You can try not minimizing the jar file, or you can expressly include the required classes in the shade config (see [this searchoverflow topic](https://stackoverflow.com/questions/8817257/minimize-an-uber-jar-correctly-using-shade-plugin) for some pointers).

**Comment by aedenj** [comment]
I tried removing the `minimizeJar` option, but still got the same error message. I checked the jar using `jar tf ...` and I do see class I'm referencing.  (`com/splunk/logging/HttpEventCollectorLoggingHandler.class`) 

Is that not sufficient to make the class discoverable by the class loader? If you have any other suggestions, that would great. Thanks for your time.
